### ISSUE TITLE
vm fault shourtly after entering user-level main

### ISSUE THREAD

**Issue by Ben-PH** [SEL4PROJ/AOS#1]
Booting on an odroidc2, i get this output

```
Jumping to kernel-image entry point...

Bootstrapping kernel
Booting all finished, dropped to user space
Caught cap fault in send phase at address 0
while trying to handle:
vm fault on code at address 0 with status 0x82000006
in thread 0xffffff807fff0400 "rootserver" at address 0
With stack:
0x513dc0: 0x513e48
0x513dc8: 0x40
0x513dd0: 0x518000
0x513dd8: 0x49c568
0x513de0: 0x1
0x513de8: 0xfffffffffffffff2
0x513df0: 0x4b5bc8
0x513df8: 0x0
0x513e00: 0x0
0x513e08: 0x0
0x513e10: 0x0
0x513e18: 0x0
0x513e20: 0x0
0x513e28: 0x0
0x513e30: 0x415924
0x513e38: 0x40a604
```

This is a fresh build, using the AOS-manifest and repo.

By moving around`while(1) {}`, this is what I can glean so far:

 * `__register_fram(&__eh_frame_start);`, and the printf triggers a fault.
 * inside `uart_init(&cspace);`, the first line function call is what triggers a fault.
 * commenting out all `printf`s and `uart_init`, it reaches `main_continued` but breaks inside `run_tests`
 * turning off the logs in there, it runs until the malloc call in `test_cspace`
 * commenting out the tests, it will break with `network_init`
 * commenting that out, it will go into `start_first_process`, ind will reach until `cspace_create_one_level`
 * will crash on `calloc` line inside `cspace_create`

**Comment by xurtis** [comment]
Can you please describe how you built the image, including the specific commands and build steps you followed?

**Comment by Ben-PH** [comment]
Lost the exact commands. In running it again:

```
mkdir tmp_sel4 && cd tmp_sel4
repo init -u https://github.com/SEL4PROJ/AOS-manifest.git
repo sync
mkdir build && cd build
../init_build.sh
ninja
ln -s ../projects/aos/reset.sh ../reset.sh
../reset.sh
```

**Comment by xurtis** [comment]
I've just pushed some changes that have been made internally since last year out to github. Can you run `repo sync` and try building again?

**Comment by Ben-PH** [comment]
did a repo sync, then ran `../init-build.sh`, got the following error.

```
CMake Error at tools/seL4/cmake-tool/helpers/application_settings.cmake:129 (message):
  KernelArmSel4Arch is no longer supported, use PLATFROM
Call Stack (most recent call first):
  settings.cmake:29 (correct_platform_strings)
  CMakeLists.txt:9 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ben/seld/build/CMakeFiles/CMakeOutput.log".
See also "/home/ben/seld/build/CMakeFiles/CMakeError.log".
```

removed that check from `tools/seL4/cmake-tool/helpers/application_settings.cmake` to see what would happen. the next `../init-build.sh` gave this output

```
-- libmuslc architecture: 'aarch64' (from KernelSel4Arch 'aarch64')
-- Detecting cached version of: musllibc
--   No cache path given. Set SEL4_CACHE_DIR to a path to enable caching binary artifacts.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ben/seld/build
```

with `ninja` got this output

```
[76/113] Building C object projects/aos/sos/CMakeFiles/sos.dir/src/elf.c.obj
../projects/aos/sos/src/elf.c: In function ‘elf_load’:
../projects/aos/sos/src/elf.c:179:29: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         char *source_addr = elf_file->elfFile + elf_getProgramHeaderOffset(elf_file, i);
                             ^~~~~~~~
[82/113] Building C object projects/aos/sos/CMakeFiles/sos.dir/src/main.c.obj
../projects/aos/sos/src/main.c: In function ‘start_first_process’:
../projects/aos/sos/src/main.c:425:22: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     char *elf_base = cpio_get_file(_cpio_archive, cpio_len, app_name, &elf_size);
                      ^~~~~~~~~~~~~
[113/113] Generating ../../../images/sos-image-arm-odroidc2
```

the new reset wasn't working. the `odroid` command not found

I manually coppied with `cp ./images/sos-image-arm-odroidc2 /var/tftpboot/ben/` and `cp apps/tty_test /var/tftpboot/ben`

got this

```
Bootstrapping kernel
Booting all finished, dropped to user space

SOS Starting...
<<seL4(CPU 0) [handleInterruptEntry/51 T0xffffff807fff0400 "SOS:root" @400650]: Spurious interrupt!>>
Found thread has no fault handler while trying to handle:
vm fault on data at address 0x8000c81002 with status 0x92000007
in thread 0xffffff807fff0400 "SOS:root" at address 0x40db9c
With stack:
0x513da0: 0x513dd0
0x513da8: 0x40b8d8
0x513db0: 0x14
0x513db8: 0xc8100000
0x513dc0: 0x0
0x513dc8: 0x8000c81000
0x513dd0: 0x513e40
0x513dd8: 0x411a1c
0x513de0: 0x514000
0x513de8: 0xc44
0x513df0: 0xc4b31
0x513df8: 0x1000
0x513e00: 0xc8100000
0x513e08: 0x519858
0x513e10: 0x1898
0x513e18: 0xc0b58
```

weirdly enough, that's the first and only time I've seen the spurious interupt. Tried re-running it a few times, didn't get it again.

**Comment by xurtis** [comment]
You probably need to remove your build directory and create a new one. You don't appear to have actually rebuilt the image with the changes.

**Comment by Ben-PH** [comment]
Made a completely new directory with a new repo init and sync. Still got the issue.


If you're not getting anything, then it must be something to do with this machine. Sorry about this.
