### ISSUE TITLE
Incorrect path in print statement

### ISSUE THREAD

**Issue by ljden** [SEL4PROJ/AOS#2]
Should be `sos/src/backtrace.h`
https://github.com/SEL4PROJ/AOS/blob/fb0e494f7a43b734dd4fa615cd21f566c9fad841/sos/src/sys/exit.c#L20

**Comment by Ivan-Velickovic** [comment]
Fixed in https://github.com/SEL4PROJ/AOS/commit/43fd45c3d8933662ae1ca6a97b92bdfeaf68e964
