### ISSUE TITLE
Function name is microseconds, implementation uses milliseconds

### ISSUE THREAD

**Issue by ljden** [SEL4PROJ/AOS#3]
https://github.com/SEL4PROJ/AOS/blob/fb0e494f7a43b734dd4fa615cd21f566c9fad841/libsosapi/src/sys_time.c#L32-L34
https://github.com/SEL4PROJ/AOS/blob/fb0e494f7a43b734dd4fa615cd21f566c9fad841/libsosapi/include/sos.h#L128-L129

**Comment by Ivan-Velickovic** [comment]
This has been fixed in https://github.com/SEL4PROJ/AOS/commit/1e18e0fab5aa46c69bb22a63e2d0b62eec466cce.
