### ISSUE TITLE
stdout_fd undeclared

### ISSUE THREAD

**Issue by linusbrogan** [SEL4PROJ/AOS#4]
When I build, I get an error here because `stdout_fd` is not in scope (since c64a1d39fbe87e6cab190680a5f913170c2c9941). Should this be `fd_out` instead?
https://github.com/SEL4PROJ/AOS/blob/1e18e0fab5aa46c69bb22a63e2d0b62eec466cce/apps/sosh/src/sosh.c#L130

**Comment by Ivan-Velickovic** [comment]
Yes, this was fixed in [`223a2ff1d7bdee50fee38c741324a56aa2020b25`](https://github.com/SEL4PROJ/AOS/commit/223a2ff1d7bdee50fee38c741324a56aa2020b25).
